server:
  port: 8082
  servlet:
    context-path: /api/products

spring:
  application:
    name: product-service
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      enabled: true
      lifecycle-management: start-only
  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    username: ecommerce
    password: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
#    locations: classpath:db/migration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.flywaydb: DEBUG
