server:
  port: 8082
  servlet:
    context-path: /api/products


app:
  openapi:
    enabled: true
    title: "Product Service API"
    description: "Product Management Service"
    version: "1.0.0"
  security:
    jwt:
      jwk-set-uri: 'http://localhost:8081/api/auth/.well-known/jwks.json'

spring:
  application:
    name: product-service
  docker:
    compose:
      enabled: false
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    username: ecommerce
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true

