server:
  port: 8082
  servlet:
    context-path: /api/products
  tomcat:
    redirect-context-root: false

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: ecommerce
    password: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    com.app: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
